fix(context): remove duplicate definition of render method (#2191)
* fix(context): remove duplicate definition of render method

The `render` method was defined twice in the `Context` class.
This duplicate definition was causing a TypeScript error below if `tsc` is used to compile the project:

```
node_modules/hono/dist/types/context.d.ts(134,5): error TS2300: Duplicate identifier 'render'.
```

* chore: denoify